# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"
  displayName: "Install Node.js"

- script: 
   npm ci
  displayName: "Install dependencies"

- script: 
   npx playwright install --with-deps
  displayName: "Install Playwright Browsers"

- script:
  npx playwright test
  displayName: "Run playwright tests"

- publish: $(System.DefaultWorkingDirectory)/playwright-report
artifact: playwright-report
condition: always()